[package]
name = "zencore_tui"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
ignore = "0.4.25"
mdbook = "0.5.1"
mlua = "0.11.5"
notify = "8.2.0"
ratatui = "0.29.0"
tokio = "1.48.0"
tui-input = "0.14.0"

